name: CODE ANALYSIS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install cppcheck
      run: sudo apt install cppcheck
    - name: make analysis
      run: make analysis
